---
abstract: unknown
author:
  - 'Rafael Garcia-Suarez <rgs@consttype.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.86, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-LongString
no_index:
  directory:
    - t
    - inc
requires:
  Test::Builder: 0.12
  Test::Builder::Tester: 1.04
resources:
  repository: https://github.com/rgs/Test-LongString.git
version: 0.17
